# Generated by Django 4.1.7 on 2023-06-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_alter_comment_author_alter_post_author'),
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
